services:
  fuller:
    hostname: fuller
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - type: bind
        source: ../results/
        target: /home/fuller/results/
      - type: bind
        source : ../data/
        target: /home/fuller/data/
      - type: bind
        source: ../scripts/
        target: /home/fuller/scripts/